def count_bases(dna_sequence):
    num_of_bases = {
        'A': 0,
        'C': 0,
        'G': 0,
        'T': 0
    }

    for base in dna_sequence:
        num_of_bases[base] = num_of_bases[base] + 1

    return num_of_bases

if __name__ == '__main__':
    dna_sequence = 'GCGTATTTTTATGTGGACATACAGCCGGTTTCACCCTGTCTATTTTGTGGGGATAATCTCCGGAGCTCTCAGAACGCCTCGCTGCTTCCTACAGGGGCTGTTTTACCTGGCCTGCGGAGACAGAGGGTTAAATTGATAACGCCTTTTGAGTAGAATGAATTGTGATGGCCAGGACGAGCCAGTTTGCCTCAGCGACTTATTACTGAAGCCATAAGCCCAGCTCCGGGTTGGGAAAAGACCTCGTATGGAAACAGGACGAACTAGGATCGCGTACTACAATGCTTGTACATCATTATGCAGAATCACAGTAGTAGTGCCGCGTTGCACATAATTCTATTCGTACTGCCTATGGCTGACCTTGTCGACAAGAGTTTATCATCGGCCAGCAACCTCACGAACAGGCACCGGCGGTGCGTGCCAGGGTCTTCGCCATCGCATACCCCTAAGGCCCTTATGAGCCTATAGAGTGTGAACCCGGGTCCTCGTGTACCTTAACCCCCCCGTCATAGTGGATCGAAGCAGTCAGAAAAAGGTTGCTGATTGGAGGGTAAATGGTTTGCTGACTAGGTACTACGCGAACCCGACCCTGCAGTTCCGTATATCCATTACATTGTTTCGTTTTAGGTCTCCTTCGGCACGTTCCTGCTGAACAAATTCACACCGTTATGATGGCTTCGAGACACGGTAACTTAGCGTCTTCTGAAGTTCGAACCTTGCGAACTTGATTCAATTATCGTTTCTTAGTGCTGCACCGCTTCTAGCACACCTTGCGTGTACTCTACGGCTTTAAATTCCCCCTTTGTGCAAGGGTCCTCATCCTGTATGCGATTAAGCGACCACAGTACTCGGCTGGCGGAGAGACCGGCTGCGTAATGAGGAGGAGGCGGGCTGTGCCATATGCGGGAGCAACAACATTTACGCGTCGAGCCATGTATAGCCTTAATCGTCGGAATGCTCACTAGGCTT'
    dict_of_bases = count_bases(dna_sequence)
    print(f"Adenosine (A): {dict_of_bases['A']}\nCytosine (C): {dict_of_bases['C']}\nGuanine (G): {dict_of_bases['G']}\nThymine (T): {dict_of_bases['T']}")
